import type { Metadata } from "next";
import { Raleway, Della_Respira } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const raleway = Raleway({ subsets: ["latin"], variable: "--font-raleway" });

const dellaRespira = Della_Respira({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-della-respira",
});

export const viewport = {
  width: "device-width",
  maximumScale: 1,
  initialScale: 1,
};

export const metadata: Metadata = {
  title: "Real Estate Photography Los Angeles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={` ${raleway.variable}  ${dellaRespira.variable} antialiased bg-[#F5F5F3] font-raleway`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
